[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
root = "./"
include = ['./src/shepherd_data', './src/examples', "./tests"]
pythonVersion = "3.8"
pythonPlatform = "All"
reportMissingParameterType = true

# TODO: switch fully to this config: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# TODO: build a light version with basic support for reading, writing (only libs that run on beaglebone)
